import { Category, Expense, Household, Member } from './types';

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'user_2',
    name: 'Natalia Gómez',
    email: 'natalia@kopar.app',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    status: 'active',
    income: 3800000,
  },
  {
    id: 'user_3',
    name: 'Mateo Morales',
    email: 'mateo@kopar.app',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'member',
    status: 'active',
    income: 3200000,
  },
];

export const INITIAL_HOUSEHOLD: Household = {
  id: 'hh_1',
  name: 'KOPAR',
  code: 'HOME-360',
  currency: '$',
  defaultSplitRule: '50_50',
  createdDate: '2026-08-01',
  coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&auto=format&fit=crop&q=80',
  members: INITIAL_MEMBERS,
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_fijos',
    name: 'Gastos Fijos',
    definition: 'Gastos que se repiten todos los meses y son imprescindibles.',
    icon: 'Home',
    budgetLimit: 3200000,
    color: '#0052ff',
    subcategories: [
      'Arriendo / Hipoteca',
      'Servicios públicos',
      'Mercado principal',
      'Administración edificio',
      'Internet hogar',
      'Transporte diario',
      'Seguro hogar',
      'Seguro médico',
      'Cuota crédito',
      'Pensión escolar',
      'Otros',
    ],
  },
  {
    id: 'cat_recurrentes',
    name: 'Gastos Recurrentes',
    definition: 'Gastos que se repiten periódicamente pero son prescindibles.',
    icon: 'Repeat',
    budgetLimit: 650000,
    color: '#7c3aed',
    subcategories: [
      'Streaming video',
      'Streaming música',
      'Membresía gimnasio',
      'Almacenamiento nube',
      'Plan celular',
      'Suscripción software',
      'Paseador mascotas',
      'Clubes membresías',
      'Clases extracurriculares',
      'Cafetería frecuente',
      'Otros',
    ],
  },
  {
    id: 'cat_ocasionales',
    name: 'Gastos Ocasionales',
    definition: 'Gastos esporádicos, planeados y prescindibles.',
    icon: 'Compass',
    budgetLimit: 850000,
    color: '#f59e0b',
    subcategories: [
      'Cena restaurante',
      'Salida bar',
      'Viajes vacaciones',
      'Domicilios comida',
      'Cine / Conciertos',
      'Ropa / Calzado',
      'Decoración hogar',
      'Regalos celebraciones',
      'Cuidado personal',
      'Escapada fin-de-semana',
      'Otros',
    ],
  },
  {
    id: 'cat_imprevistos',
    name: 'Gastos Imprevistos',
    definition: 'Gastos no planeados pero que resultan imprescindibles.',
    icon: 'AlertTriangle',
    budgetLimit: 500000,
    color: '#f0616d',
    subcategories: [
      'Consulta médica',
      'Compra medicamentos',
      'Urgencia veterinaria',
      'Reparación hogar',
      'Reparación vehículo',
      'Mantenimiento bicicleta',
      'Reemplazo electrodoméstico',
      'Trámites urgentes',
      'Servicio plomería',
      'Servicio cerrajería',
      'Otros',
    ],
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp_1',
    title: 'Cena de bienvenida en restaurante',
    subcategory: 'Cena restaurante',
    amount: 180000,
    categoryId: 'cat_ocasionales',
    paidById: 'user_2',
    date: '2026-08-12',
    status: 'PAGADO',
    notes: 'Restaurante El Jardín - Cena compartida',
    createdAt: new Date('2026-08-12T14:30:00').toISOString(),
    splits: [
      { memberId: 'user_2', amount: 90000, percentage: 50 },
      { memberId: 'user_3', amount: 90000, percentage: 50 },
    ],
  },
  {
    id: 'exp_2',
    title: 'Internet fibra óptica 300MB',
    subcategory: 'Internet hogar',
    amount: 110000,
    categoryId: 'cat_fijos',
    paidById: 'user_2',
    date: '2026-08-10',
    status: 'PENDIENTE',
    notes: 'Recibo mensual de internet del hogar',
    createdAt: new Date('2026-08-10T09:15:00').toISOString(),
    splits: [
      { memberId: 'user_2', amount: 55000, percentage: 50 },
      { memberId: 'user_3', amount: 55000, percentage: 50 },
    ],
  },
  {
    id: 'exp_3',
    title: 'Mercado quincenal principal',
    subcategory: 'Mercado principal',
    amount: 480000,
    categoryId: 'cat_fijos',
    paidById: 'user_3',
    date: '2026-08-08',
    status: 'DEBES',
    notes: 'Mercado de frutas, verduras, carnes y aseo',
    createdAt: new Date('2026-08-08T18:00:00').toISOString(),
    splits: [
      { memberId: 'user_2', amount: 240000, percentage: 50 },
      { memberId: 'user_3', amount: 240000, percentage: 50 },
    ],
  },
  {
    id: 'exp_4',
    title: 'Streaming video y entretenimiento',
    subcategory: 'Streaming video',
    amount: 65000,
    categoryId: 'cat_recurrentes',
    paidById: 'user_3',
    date: '2026-08-05',
    status: 'DEBES',
    notes: 'Suscripción mensual a plataformas',
    createdAt: new Date('2026-08-05T11:20:00').toISOString(),
    splits: [
      { memberId: 'user_2', amount: 32500, percentage: 50 },
      { memberId: 'user_3', amount: 32500, percentage: 50 },
    ],
  },
  {
    id: 'exp_5',
    title: 'Servicio plomería urgente cocina',
    subcategory: 'Servicio plomería',
    amount: 140000,
    categoryId: 'cat_imprevistos',
    paidById: 'user_2',
    date: '2026-08-03',
    status: 'PAGADO',
    notes: 'Reparación de filtración en tubería del lavaplatos',
    createdAt: new Date('2026-08-03T16:40:00').toISOString(),
    splits: [
      { memberId: 'user_2', amount: 70000, percentage: 50 },
      { memberId: 'user_3', amount: 70000, percentage: 50 },
    ],
  },
];
